version: 2
updates:
  # Update Ionic dependencies
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "daily"

  # Update Electron dependencies
  - package-ecosystem: "npm"
    directory: "/electron"
    target-branch: "dev"
    schedule:
      interval: "daily"
