require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'ByteowlsCapacitorFilesharer', :path => '..\..\node_modules\@byteowls\capacitor-filesharer'
  pod 'CapacitorApp', :path => '..\..\node_modules\@capacitor\app'
  pod 'CapacitorClipboard', :path => '..\..\node_modules\@capacitor\clipboard'
  pod 'CapacitorKeyboard', :path => '..\..\node_modules\@capacitor\keyboard'
  pod 'CapacitorPreferences', :path => '..\..\node_modules\@capacitor\preferences'
  pod 'CapacitorScreenReader', :path => '..\..\node_modules\@capacitor\screen-reader'
  pod 'CapacitorSplashScreen', :path => '..\..\node_modules\@capacitor\splash-screen'
  pod 'CapacitorStatusBar', :path => '..\..\node_modules\@capacitor\status-bar'
  pod 'CapacitorToast', :path => '..\..\node_modules\@capacitor\toast'
  pod 'CapacitorSecureStoragePlugin', :path => '..\..\node_modules\capacitor-secure-storage-plugin'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end


post_install do |installer|
  assertDeploymentTarget(installer)
end
