name: Build WebUI

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: npm install

      - name: Pre-build
        run: npm run-script prebuild:webui

      - name: Build
        run: npm run build
        
      - name: Post-build
        run: npm run-script postbuild:webui

      - name: Create zip
        run: zip -r release.zip ./dist/

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: Transmissionic-webui-${{ github.event.release.tag_name }}.zip
          path: ./release.zip
