# This is a basic workflow to help you get started with Actions

name: Build Electron Windows

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: |
          npm install
          npm install -g @ionic/cli
          npm install -g @capacitor/cli

      - name: Build
        run: ionic capacitor sync @capacitor-community/electron
      
      - name: Post-build
        run: npm run-script postbuild:electron

      - name: Install electron dependencies
        working-directory: ./electron
        run: npm install

      - name: Build electron
        working-directory: ./electron
        run: npm run-script electron:build-windows

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./electron/dist/Transmissionic-win-${{ github.event.release.tag_name }}.exe
          asset_name: Transmissionic-win-${{ github.event.release.tag_name }}.exe
          asset_content_type: application/octet-stream
