name: Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  dependencies:
    name: Create draft release and install dependencies
    runs-on: ubuntu-latest
    outputs: 
      version: v${{steps.version.outputs.prop}}
      upload_url: ${{ steps.create_release.outputs.upload_url }} 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with: 
            path: 'package.json'
            prop_path: 'version'

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{steps.version.outputs.prop}}
          release_name: v${{steps.version.outputs.prop}}
          draft: true
          prerelease: false

  build-webui:
    name: Build WebUI
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: npm ci

      - name: Pre-build
        run: npm run-script prebuild:webui

      - name: Build
        run: npm run build

      - name: Post-build
        run: npm run-script postbuild:webui

      - name: Create zip
        run: |
          mv ./dist/ ./web/
          zip -r release.zip ./web/

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.dependencies.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: Transmissionic-webui-${{ needs.dependencies.outputs.version }}.zip
          asset_content_type: application/zip

  build-electron-linux:
    name: Build Electron Linux
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: |
          npm install
          npm install -g @ionic/cli
          npm install -g @capacitor/cli

      - name: Build
        run: ionic capacitor sync @capacitor-community/electron
      
      - name: Post-build
        run: npm run-script postbuild:electron

      - name: Install electron dependencies
        working-directory: ./electron
        run: npm ci

      - name: Build electron
        working-directory: ./electron
        run: npm run-script electron:build-linux

      - name: Upload amd64 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.dependencies.outputs.upload_url }}
          asset_path: ./electron/dist/Transmissionic-linux-amd64-${{ needs.dependencies.outputs.version }}.deb
          asset_name: Transmissionic-linux-amd64-${{ needs.dependencies.outputs.version }}.deb
          asset_content_type: application/octet-stream

      - name: Upload i386 Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.dependencies.outputs.upload_url }}
          asset_path: ./electron/dist/Transmissionic-linux-i386-${{ needs.dependencies.outputs.version }}.deb
          asset_name: Transmissionic-linux-i386-${{ needs.dependencies.outputs.version }}.deb
          asset_content_type: application/octet-stream

  build-electron-win:
    name: Build Electron Windows
    needs: dependencies
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: |
          npm install
          npm install -g @ionic/cli
          npm install -g @capacitor/cli

      - name: Build
        run: ionic capacitor sync @capacitor-community/electron
      
      - name: Post-build
        run: npm run-script postbuild:electron

      - name: Install electron dependencies
        working-directory: ./electron
        run: npm ci

      - name: Build electron
        working-directory: ./electron
        run: npm run-script electron:build-windows

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.dependencies.outputs.upload_url }}
          asset_path: ./electron/dist/Transmissionic-win-${{ needs.dependencies.outputs.version }}.exe
          asset_name: Transmissionic-win-${{ needs.dependencies.outputs.version }}.exe
          asset_content_type: application/octet-stream

  build-android:
    name: Build Android
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: c-hive/gha-npm-cache@v1

      - name: Install dependencies
        run: |
          npm ci
          npm install -g @ionic/cli
          npm install -g @capacitor/cli

      - name: Build
        run: ionic capacitor sync android

      - name: Build APK
        working-directory: ./android
        run: |
          chmod +x gradlew
          ./gradlew build

      - uses: r0adkll/sign-android-release@v1
        name: Sign APK
        id: sign_app
        with:
          releaseDirectory: ./android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.dependencies.outputs.upload_url }}
          asset_path: ${{steps.sign_app.outputs.signedReleaseFile}}
          asset_name: Transmissionic-android-${{ needs.dependencies.outputs.version }}.apk
          asset_content_type: application/zip
