name: Build Electron Windows

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies
        run: |
          npm install
          npm install -g @ionic/cli
          npm install -g @capacitor/cli

      - name: Build
        run: ionic capacitor sync @capacitor-community/electron
      
      - name: Post-build
        run: npm run-script postbuild:electron

      - name: Install electron dependencies
        working-directory: ./electron
        run: npm install

      - name: Build electron
        working-directory: ./electron
        run: npm run-script electron:build-windows

      - name: Upload Release Asset
        uses: actions/upload-artifact@v2
        with:
          name: Transmissionic-win-${{ github.event.release.tag_name }}.exe
          path: ./electron/dist/Transmissionic-win-${{ github.event.release.tag_name }}.exe
